MedicalSpecialties = [
  'Alergología',
  'Anatomía Patológica',
  'Anestesiología Pediátrica',
  'Anestesiología y Recuperación',
  'Auditoría Médica',
  'Cardiología',
  'Cardiología Pediátrica',
  'Cirugía de Tórax y Cardiovascular',
  'Cirugía General',
  'Cirugía Pediátrica',
  'Cirugía Plástica y Reconstructiva',
  'Cirugía Torácica General',
  'Dermatología',
  'Endocrinología',
  'Gastroenterología',
  'Geriatría y Gerontología',
  'Ginecología Oncológica',
  'Ginecología y Obstetricia',
  'Hematología',
  'Hematología Pediátrica',
  'Homeopatía',
  'Infectología',
  'Infectología Pediátrica',
  'Inmunología Clínica Médica',
  'Medicina Crítica Pediátrica',
  'Medicina Crítica y Terapia Intensiva',
  'Medicina de Emergencias',
  'Medicina Familiar y Comunitaria',
  'Medicina Física y Rehabilitación',
  'Medicina Interna',
  'Medicina Laboral',
  'Medicina Materno Fetal',
  'Medicina Paliativa en Adultos',
  'Nefrología',
  'Nefrología Pediátrica',
  'Neonatología',
  'Neumología',
  'Neumología Pediátrica',
  'Neurocirugía',
  'Neurología',
  'Odontología',
  'Oftalmología',
  'Oftalmología Pediátrica',
  'Oncología Médica',
  'Oncología Quirúrgica',
  'Ortopedia y Traumatología',
  'Ortopedia y Traumatología Infantil',
  'Otorrinolaringología',
  'Patología Pediátrica',
  'Pediatría',
  'Psicología Clínica',
  'Psiquiatría',
  'Radiología e Imágenes Médicas',
  'Radioterapia',
  'Reumatología',
  'Terapia Física',
  'Urología',
  'Urología Pediátrica'
]
